apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mongodb.operator.fullname" . }}-operator
  labels:
    {{- include "mongodb.operator.labels" . | nindent 4 }}
    {{- if .Values.additionalLabels -}}
    {{- toYaml .Values.additionalLabels | nindent 4 -}}    
    {{- end -}}
    {{- if .Values.mongodb.additionalLabels }}
    {{- with .Values.mongodb.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: mongodb-kubernetes-operator
roleRef:
  kind: Role
  name: {{ include "mongodb.operator.fullname" . }}-operator
  apiGroup: rbac.authorization.k8s.io
