apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "mongodb.operator.fullname" . }}-operator
  labels:
    {{- include "mongodb.operator.labels" . | nindent 4 }}
    {{- if .Values.additionalLabels -}}
    {{- toYaml .Values.additionalLabels | nindent 4 -}}    
    {{- end -}}
    {{- if .Values.mongodb.additionalLabels }}
    {{- with .Values.mongodb.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - {{ include "mongodb.operator.fullname" . }}-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - mongodb.com
  resources:
  - '*'
  - mongodbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- if .Values.operator.podSecurityPolicy.enabled }}
  - apiGroups:
      - extensions
    resourceNames:
      - {{ include "mongodb.operator.fullname" . }}-operator
    resources:
      - podsecuritypolicies
    verbs:
      - use
{{- end -}}