apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-kubernetes-operator
  labels:
    {{- include "mongodb.operator.labels" . | nindent 4 }}
    {{- if .Values.additionalLabels -}}
    {{- toYaml .Values.additionalLabels | nindent 4 -}}    
    {{- end -}}
    {{- if .Values.mongodb.additionalLabels }}
    {{- with .Values.mongodb.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
